#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <QDomDocument>
#include <QHash>

namespace PENGUIN {
enum DIRECTION {
    S,
    SW,
    W,
    NW,
    N,
    NE,
    E,
    SE,
};

enum STATE {
    STANDING,
    SITTING,
    WALKING,
    DANCING,
    WAVING,
    SNOWBALL,
    NINJA,
    UNUSED
};

struct SPRITEINFO {
    DIRECTION direction;
    STATE state;

};

const QHash<int, PENGUIN::SPRITEINFO> spritesMapped = {
    {1,SPRITEINFO{DIRECTION::S,STATE::STANDING}},
    {2,SPRITEINFO{DIRECTION::SW,STATE::STANDING}},
    {3,SPRITEINFO{DIRECTION::W,STATE::STANDING}},
    {4,SPRITEINFO{DIRECTION::NW,STATE::STANDING}},
    {5,SPRITEINFO{DIRECTION::N,STATE::STANDING}},
    {6,SPRITEINFO{DIRECTION::NE,STATE::STANDING}},
    {7,SPRITEINFO{DIRECTION::E,STATE::STANDING}},
    {8,SPRITEINFO{DIRECTION::SE,STATE::STANDING}},
    {9,SPRITEINFO{DIRECTION::S,STATE::WALKING}},
    {10,SPRITEINFO{DIRECTION::SW,STATE::WALKING}},
    {11,SPRITEINFO{DIRECTION::W,STATE::WALKING}},
    {12,SPRITEINFO{DIRECTION::NW,STATE::WALKING}},
    {13,SPRITEINFO{DIRECTION::N,STATE::WALKING}},
    {14,SPRITEINFO{DIRECTION::NE,STATE::WALKING}},
    {15,SPRITEINFO{DIRECTION::E,STATE::WALKING}},
    {16,SPRITEINFO{DIRECTION::SE,STATE::WALKING}},
    {17,SPRITEINFO{DIRECTION::S,STATE::SITTING}},
    {18,SPRITEINFO{DIRECTION::SW,STATE::SITTING}},
    {19,SPRITEINFO{DIRECTION::W,STATE::SITTING}},
    {20,SPRITEINFO{DIRECTION::NW,STATE::SITTING}},
    {21,SPRITEINFO{DIRECTION::N,STATE::SITTING}},
    {22,SPRITEINFO{DIRECTION::NE,STATE::SITTING}},
    {23,SPRITEINFO{DIRECTION::E,STATE::SITTING}},
    {24,SPRITEINFO{DIRECTION::SE,STATE::SITTING}},
    {25,SPRITEINFO{DIRECTION::S,STATE::WAVING}},
    {26,SPRITEINFO{DIRECTION::S,STATE::DANCING}},
    {27,SPRITEINFO{DIRECTION::SW,STATE::SNOWBALL}},
    {28,SPRITEINFO{DIRECTION::NW,STATE::SNOWBALL}},
    {29,SPRITEINFO{DIRECTION::NE,STATE::SNOWBALL}},
    {30,SPRITEINFO{DIRECTION::SE,STATE::SNOWBALL}},
    {31,SPRITEINFO{DIRECTION::S,STATE::UNUSED}},
    {32,SPRITEINFO{DIRECTION::S,STATE::UNUSED}},
    {33,SPRITEINFO{DIRECTION::E,STATE::NINJA}},
    {34,SPRITEINFO{DIRECTION::W,STATE::NINJA}},
    {35,SPRITEINFO{DIRECTION::SE,STATE::NINJA}},
    {36,SPRITEINFO{DIRECTION::NW,STATE::NINJA}},
    {37,SPRITEINFO{DIRECTION::SW,STATE::NINJA}},
    {38,SPRITEINFO{DIRECTION::NE,STATE::NINJA}}
    };

enum BADGE {
    NONE,
    PLAYER,
    MEMBER_0,
    MEMBER_1,
    MEMBER_2,
    MEMBER_3,
    MEMBER_4
};
};
namespace CLOTHES {
enum TYPE {
    COLOR=1,
    HEAD,
    FACE,
    NECK,
    BODY,
    HAND,
    FEET,
    PIN,
    BACKGROUND,
    AWARD
};
}
namespace CANVAS {
enum ACTION {
    CLICKABLE = 1,
    HOVERABLE = 2,
    MOUSE_TRACKABLE = 4
};
/*struct Frame {
    int xmin = 0;
    int xmax = 0;
    int ymin = 0;
    int ymax = 0;
    QDomDocument r;
};*/
}

#endif // CONSTANTS_H
